stages:
  - deploy

deploy:
  stage: deploy
  image: node:20-alpine
  script:
    - npm i --legacy-peer-deps
    - npm run build
    - apk install zip sftp
    - zip -r xpertnet.zip .
    - sshpass -p "$FTP_PASS" sftp "$FTP_USER@$FTP_HOST:xpertnet.ch" <<< $'put xpertnet.zip'
  environment:
    name: production
  only:
    - main
