name: Deployment to ServerTown
run-name: Deploying the Xpernet website to the PHP servers of ServerTown
on: [push]
jobs:
  Deployment:
    runs-on: node:20-alpine
    steps:
      - npm i --legacy-peer-deps
      - npm run build
      - pkg install zip
      - zip -r xpertnet.zip .
