name: Deployment to ServerTown
run-name: Deploying the Xpernet website to the PHP servers of ServerTown
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Deployment:
    runs-on: node:20-alpine
    steps:
      - run: npm i --legacy-peer-deps
      - run: npm run build
      - run: pkg install zip
      - run: zip -r xpertnet.zip .
